### ISSUE TITLE
Cannot create 2 private endpoints for the same Vnet

### ISSUE THREAD

**Issue by ecstaticrainbow** [UKHO/tfmodule-azure-private-endpoint-private-link#7]
Because the module creates a `azurerm_private_dns_zone_virtual_network_link` for every instance of the module, if you are trying to create 2 private endpoints for 2 separate services inside the same vnet, the terraform will always fail with a conflict as azure will respond with `Private zone 'privatelink.azurewebsites.net' is already linked to the virtual network`

See https://github.com/UKHO/email-service/blob/add-terraform-for-ui-app/Deployment/Terraform/main.tf#L241-L276 for a reproduction

**Comment by ShaunBresnahan** [comment]
Bug now resolved. Please use new ref.
